version: 2.1
orbs:
  codecov: codecov/codecov@4

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests with coverage
          command: |
            coverage run -m pytest
      - codecov/upload

workflows:
  version: 2.1
  build-test:
    jobs:
      - build
